### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by oliveskur** [Wandmalfarbe/ROM-Metadata-Reader#1]
Can't compile it - some classes are unfinished.
public class GbMetadata doesn't contain following methods: setTitle, setGameCode, setCgbFlag, setNewLicenseeCode, setSgbFlag, setCartridgeType, setRomSize, setRamSize, setDestinationCode, setOldLicenseeCode, setMaskRomVersionNumber, setHeaderChecksum.
public class GbaMetadata doesn't contain following methods: setTitle, setGameCode, setMakerCode, setUnitCode, setVersionCode, setHeaderChecksum.
public class NdsMetadata doesn't contain following methods: setTitle, setGameCode, setMakerCode, setUnitCode.
public abstract class RomFileTypeDetector doesn't contain method getShortType.

**Comment by Wandmalfarbe** [comment]
This is generated lombok code. You need to install the [lombok plugin for your IDE](https://projectlombok.org/) and enable annotation processing (in IntelliJ IDEA).

The lombok dependency should automatically be available when you import as a Maven project from the `pom.xml`.
